spring.application.name=blog-platform

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=12


application.description=REST API for Blog Platform using Spring Boot & JWT Security
application.version=1.0

#spring.security.user.name=abdo
#spring.security.user.password=abdo123


