spring.config.activate.on-profile=prod

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.hibernate.ddl-auto=validate

logging.level.root=warn
spring.main.banner-mode=off


# management.endpoint.health.show-details=never
spring.jpa.open-in-view=false

# hikari configurations
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000



application.description=REST API for Blog Platform using Spring Boot & JWT Security
application.version=1.0



