spring.application.name=blog-platform

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=12

spring.jpa.hibernate.ddl-auto=update

# Swagger Config
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


application.description=REST API for Blog Platform using Spring Boot & JWT Security
application.version=1.0



