spring.config.activate.on-profile=prod

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.hibernate.ddl-auto=validate

logging.level.root=warn
spring.main.banner-mode=off


# management.endpoint.health.show-details=never
spring.jpa.open-in-view=false

application.description=REST API for Blog Platform using Spring Boot & JWT Security
application.version=1.0

#spring.security.user.name=abdo
#spring.security.user.password=abdo123


