spring.config.activate.on-profile=dev

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
logging.level.org.springframework=debug



application.description=REST API for Blog Platform using Spring Boot & JWT Security
application.version=1.0

#spring.security.user.name=abdo
#spring.security.user.password=abdo123


